name: Generate PDF Resume
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert Markdown to PDF
        run: |
          pandoc index.md -o assets/john_priftis_resume.pdf \
          --pdf-engine=xelatex \
          -V geometry:margin=1in \
          -V fontsize=12pt

      - name: Upload PDF
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: resume-pdf
          path: assets/john_priftis_resume.pdf

      - name: Commit and Push PDF
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/john_priftis_resume.pdf
          git commit -m "Update PDF resume [skip ci]"
          git push
