name: Generate PDF from index.md

on:
  push:
    paths:
      - index.md

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install pandoc and LaTeX (for PDF support)
      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      # Step 3: Convert index.md to resume.pdf
      - name: Generate PDF
        run: pandoc index.md -o resume.pdf --pdf-engine=xelatex

      # Step 4: Commit and push the PDF
      - name: Commit and push PDF
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add resume.pdf
          git diff --cached --quiet || git commit -m "Auto-generate resume.pdf from index.md"
          git push
